#!/usr/bin/env python3
"""Generate the Markdown guide and offline browser data from one reviewed source."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    data = json.loads((ROOT / 'data/episodes.json').read_text())
    episodes = data['episodes']
    arcs = {a['id']: a['name'] for a in data['arcs']}
    assert len(episodes) == data['selectionCount']
    assert len({e['episode'] for e in episodes}) == len(episodes)
    assert episodes == sorted(episodes, key=lambda e: e['episode'])
    assert len({e['imdb']['id'] for e in episodes}) == len(episodes)
    rated = sum(e['imdb']['rating'] is not None for e in episodes)
    text = f'''# Detective Conan: Main-Story Watch Guide

**{len(episodes)} episodes · 9 arcs · {rated} individual IMDb ratings · Updated {data['updated']}**

[Interactive watchlist](index.html) · [Episode data](data/episodes.json)

## Contents

- [Quick notes](#quick-notes)
- [Episode checklist](#episode-checklist)
- [Sources and ratings](#sources-and-ratings)

## Quick notes

Use **original Japanese episode numbers** and watch in order. Services may split long specials; match by title when numbers differ. Movies are optional.

This fan-curated route follows the central story and its prerequisites, not every manga-canon case. Selection reviewed through episode {data['coverageThrough']}; the final included episode is {episodes[-1]['episode']}. Titles and source pages can contain spoilers.

**CORE:** central-story selection. **SETUP:** prerequisite. Mark ☐ as ☑ in your copy, or use the interactive watchlist for automatic progress saving.

## Episode checklist

One row per episode. Titles link to Detective Conan World; ratings link to the exact IMDb entry. Scores are out of 10, checked **{data['updated']}**.

| Seen | Episode | Title / source | Arc | Priority | IMDb /10 | Votes |
|:---:|---:|---|---|:---:|---:|---:|
'''
    for e in episodes:
        imdb = e['imdb']
        rating = f"{imdb['rating']:.1f}" if imdb['rating'] is not None else 'N/A'
        votes = f"{imdb['votes']:,}" if imdb['votes'] is not None else 'N/A'
        title = e['title'].replace('|', '\\|')
        text += f"| ☐ | {e['episode']} | [{title}]({e['source']}) | {e['arc']}. {arcs[e['arc']]} | {e['priority']} | [{rating}](https://www.imdb.com/title/{imdb['id']}/) | {votes} |\n"
    text += '''
## Sources and ratings

[Detective Conan World](https://www.detectiveconanworld.com/wiki/Anime) supplies Japanese titles, original broadcasts, and case references. [XerBlade](https://www.xerblade.com/p/detective-conan-important-episode-list.html) informed the original guide's selection. This revision preserves the [original main table's 255 episodes](https://github.com/SawabS/DetectiveConanMainPlot/blob/ae0cfc796ae774a250dc39812cd12c0dd17668c5/detective_conan_main_story_watch_guide.md); its former 259 count and 262-episode compact list were inconsistent.

Ratings and votes come from [IMDb's non-commercial datasets](https://developer.imdb.com/non-commercial-datasets/): [episode IDs](https://datasets.imdbws.com/title.episode.tsv.gz), [titles](https://datasets.imdbws.com/title.basics.tsv.gz), and [ratings](https://datasets.imdbws.com/title.ratings.tsv.gz). IMDb uses different season numbering. Mappings were checked by title, year, and multipart order, including translated title variants; reruns were excluded. IMDb scores are weighted user ratings and change over time.

[Episode data](data/episodes.json) records each IMDb ID, IMDb title and numbering, mapping method, vote count, check date, and selection-source permalink. `N/A`, if present after a refresh, means no rating was returned for that mapped entry. See [CHANGELOG](CHANGELOG.md) for corrections.
'''
    js = '// Generated by scripts/build.py. Edit data/episodes.json instead.\nwindow.CONAN_DATA = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/') + ';\n'
    return {'detective_conan_main_story_watch_guide.md': text, 'assets/episodes.js': js}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated files are stale.')
    args = parser.parse_args()
    for name, content in outputs().items():
        assert chr(8212) not in content, f'Em dash in {name}'
        path = ROOT / name
        if args.check:
            assert path.exists() and path.read_text() == content, f'{name} is stale. Run python3 scripts/build.py'
        else:
            path.write_text(content)
    print('Generated files are current.' if args.check else 'Generated guide and browser data.')


if __name__ == '__main__':
    main()
