#!/usr/bin/env python3
"""Generate the Markdown guide and offline browser data from one reviewed source."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    data = json.loads((ROOT / 'data/episodes.json').read_text())
    episodes = data['episodes']
    arcs = {a['id']: a['name'] for a in data['arcs']}
    assert len(episodes) == data['selectionCount']
    assert len({e['episode'] for e in episodes}) == len(episodes)
    assert episodes == sorted(episodes, key=lambda e: e['episode'])
    assert len({e['imdb']['id'] for e in episodes}) == len(episodes)
    rated = sum(e['imdb']['rating'] is not None for e in episodes)
    text = f'''# Detective Conan: Main-Story Watch Guide

**{len(episodes)} episodes · 9 arcs · {rated} individual IMDb ratings · Updated {data['updated']}**

[Interactive watchlist](index.html) · [Episode data](data/episodes.json)

## Contents

- [Quick notes](#quick-notes)
- [Episode checklist](#episode-checklist)
- [Sources and ratings](#sources-and-ratings)

## Quick notes

Use **original Japanese episode numbers** and watch in order. Services may split long specials; match by title when numbers differ. Movies are optional. [Browse the complete movie checklist](detective_conan_movies.md).

This fan-curated route follows the central story and its prerequisites, not every manga-canon case. Selection reviewed through episode {data['coverageThrough']}; the final included episode is {episodes[-1]['episode']}. Titles and source pages can contain spoilers.

**CORE:** central-story selection. **SETUP:** prerequisite. Mark ☐ as ☑ in your copy, or use the interactive watchlist for automatic progress saving.

## Episode checklist

Listed minutes come from [TVmaze](https://www.tvmaze.com/), under [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/). Broadcast listings may include advertising and differ from streaming playback. [Analytics methodology](data/analytics-methodology.md).

One row per episode. Titles link to Detective Conan World; ratings link to the exact IMDb entry. Scores are out of 10, checked **{data['updated']}**.

| Seen | Episode | Title / source | Arc | Priority | IMDb /10 | Votes | Listed min |
|:---:|---:|---|---|:---:|---:|---:|---:|
'''
    for e in episodes:
        imdb = e['imdb']
        rating = f"{imdb['rating']:.1f}" if imdb['rating'] is not None else 'N/A'
        votes = f"{imdb['votes']:,}" if imdb['votes'] is not None else 'N/A'
        title = e['title'].replace('|', '\\|')
        text += f"| ☐ | {e['episode']} | [{title}]({e['source']}) | {e['arc']}. {arcs[e['arc']]} | {e['priority']} | [{rating}](https://www.imdb.com/title/{imdb['id']}/) | {votes} | [{e['runtimeMinutes']}]({e['runtimeSource']}) |\n"
    text += '''
## Sources and ratings

[Detective Conan World](https://www.detectiveconanworld.com/wiki/Anime) supplies Japanese titles, original broadcasts, and case references. [XerBlade](https://www.xerblade.com/p/detective-conan-important-episode-list.html) provides a reference for central-story cases and prerequisites. This checklist contains 255 distinct episodes across nine arcs.

Ratings and votes come from [IMDb's non-commercial datasets](https://developer.imdb.com/non-commercial-datasets/): [episode IDs](https://datasets.imdbws.com/title.episode.tsv.gz), [titles](https://datasets.imdbws.com/title.basics.tsv.gz), and [ratings](https://datasets.imdbws.com/title.ratings.tsv.gz). IMDb uses different season numbering. Mappings were checked by title, year, and multipart order, including translated title variants; reruns were excluded. IMDb scores are weighted user ratings and change over time.

[Episode data](data/episodes.json) records each IMDb ID, IMDb title and numbering, mapping method, vote count, check date, runtime, duration source, and mapping audit trail. `N/A`, if present after a refresh, means no rating was returned for that mapped entry. See [CHANGELOG](CHANGELOG.md) for corrections.
'''
    js = '// Generated by scripts/build.py. Edit data/episodes.json instead.\nwindow.CONAN_DATA = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/') + ';\n'
    result = {'detective_conan_main_story_watch_guide.md': text, 'assets/episodes.js': js}
    movie_data = json.loads((ROOT / 'data/movies.json').read_text())
    movies = movie_data['movies']
    assert len({m['id'] for m in movies}) == len(movies)
    main = [m for m in movies if m['category'] == 'main']
    assert [m['number'] for m in main] == list(range(1, len(main) + 1))
    labels = {'main': 'Main film', 'crossover': 'Crossover', 'compilation': 'Compilation', 'short': '3D short'}
    movie_text = f'''# Detective Conan / Case Closed: Movie Checklist

**{len(main)} main films + {len(movies) - len(main)} extras · Catalog checked {movie_data['updated']}**

[Interactive movie library](index.html#movies) · [Main-story episodes](detective_conan_main_story_watch_guide.md) · [Movie data](data/movies.json)

## Contents

- [Scope](#scope)
- [Movie checklist](#movie-checklist)
- [Sources](#sources)

## Scope

Released numbered theatrical films, the theatrical crossover, compilation films, and 3D shorts. TV specials, OVAs, and unreleased films are excluded. Dates are original Japanese releases; international titles and release dates may differ.

## Movie checklist

Release order. Mark ☐ as ☑ in your copy, or save progress in the interactive library. Listed runtime is in minutes. IMDb scores were checked **{movie_data['ratingsUpdated']}**; N/A means no verified score is available.

| Seen | Film | Title / source | Category | Japan release | Minutes | IMDb /10 | Votes |
|:---:|:---:|---|---|:---:|---:|---:|---:|
'''
    for movie in sorted(movies, key=lambda m: m['releaseDate']):
        number = str(movie['number']).zfill(2) if movie['number'] else 'Extra'
        runtime = movie['runtimeMinutes'] if movie['runtimeMinutes'] else 'N/A'
        imdb = movie['imdb']
        rating = f"[{imdb['rating']:.1f}](https://www.imdb.com/title/{imdb['id']}/)" if imdb['rating'] is not None else 'N/A'
        votes = f"{imdb['votes']:,}" if imdb['votes'] is not None else 'N/A'
        movie_text += f"| ☐ | {number} | [{movie['title']}]({movie['source']}) | {labels[movie['category']]} | {movie['releaseDate']} | [{runtime}]({movie['runtimeSource']}) | {rating} | {votes} |\n"
    movie_text += '''
## Sources

[Detective Conan World movie catalog](https://www.detectiveconanworld.com/wiki/Movies) provides numbering, categories, original release dates, and runtimes. Each row links to its individual film entry. Film 29 uses its linked IMDb runtime. The [TMS official catalog](https://www.tms-e.co.jp/global/alltitles/conan/) corroborates the main film titles, including the 2026 release, *Fallen Angel of the Highway*.

[IMDb non-commercial datasets](https://developer.imdb.com/non-commercial-datasets/) provide ratings and votes for 33 verified film matches. Two 3D shorts have no verified IMDb match. Scores change over time. [Analytics methodology](data/analytics-methodology.md) explains coverage and calculations.

[Movie data](data/movies.json) records the source, official page when available, and artwork source for each entry. Covers belong to their respective rights holders. Movie checkoffs and backups are separate from episode progress.
'''
    result['detective_conan_movies.md'] = movie_text
    result['assets/movies-data.js'] = '// Generated by scripts/build.py. Edit data/movies.json instead.\nwindow.CONAN_MOVIES = ' + json.dumps(movie_data, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/') + ';\n'
    from render_guides import render_pages
    result.update(render_pages(result))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated files are stale.')
    args = parser.parse_args()
    for name, content in outputs().items():
        assert chr(8212) not in content, f'Em dash in {name}'
        path = ROOT / name
        if args.check:
            assert path.exists() and path.read_text() == content, f'{name} is stale. Run python3 scripts/build.py'
        else:
            path.write_text(content)
    print('Generated files are current.' if args.check else 'Generated guide and browser data.')


if __name__ == '__main__':
    main()
